import { FormEvent, useState } from "react";
import { useNavigate, useOutletContext, useParams } from "react-router-dom";
import { Icon } from "../../components/ui/Icon";
import { PageHeader } from "../../components/ui/PageHeader";
import { Spinner } from "../../components/ui/StateViews";
import { api } from "../../lib/api";
import { canWriteWorkspace } from "../../lib/permissions";
import { AppShellContext } from "../../layouts/AppShell";

export function NewTargetPage() {
  const { applicationId = "" } = useParams(); const navigate = useNavigate(); const { workspace } = useOutletContext<AppShellContext>();
  const [name,setName]=useState(""); const [environment,setEnvironment]=useState("local"); const [baseUrl,setBaseUrl]=useState("http://localhost:3000/"); const [requiresAuth,setRequiresAuth]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  if (!canWriteWorkspace(workspace.role)) return <><PageHeader eyebrow="Target" title="Add environment" /><div className="error-panel" role="alert"><div><strong>Read-only workspace</strong><span>Your workspace role cannot create targets.</span></div></div></>;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); try { const target=await api.createTarget(applicationId,{name:name.trim(),environment,base_url:baseUrl.trim(),requires_auth:requiresAuth}); navigate(`/targets/${target.id}/authorization`); } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "Could not create target."); } finally { setBusy(false); } }
  return <><PageHeader eyebrow="Application target" title="Add environment" description="MarketTwin derives the initial allowed origin from the base URL. Additional network origins stay blocked until explicitly supported." /><div className="two-column-layout"><form className="panel form-grid" onSubmit={submit}><label className="field-label" htmlFor="target-name">Target name</label><input id="target-name" className="text-input" value={name} onChange={(event)=>{setName(event.target.value);setError(null);}} placeholder="Local storefront" required autoFocus /><label className="field-label" htmlFor="environment">Environment</label><select id="environment" className="text-input" value={environment} onChange={(event)=>setEnvironment(event.target.value)}><option value="local">Local</option><option value="development">Development</option><option value="qa">QA</option><option value="staging">Staging</option><option value="demo">Demo</option><option value="production">Production</option></select><label className="field-label" htmlFor="base-url">Base URL</label><input id="base-url" className="text-input" type="url" value={baseUrl} onChange={(event)=>{setBaseUrl(event.target.value);setError(null);}} required spellCheck={false} /><label className="toggle-row"><span><strong>Protected experience</strong><small>This target requires login or another authentication step.</small></span><input type="checkbox" checked={requiresAuth} onChange={(event)=>setRequiresAuth(event.target.checked)} /></label>{error ? <p className="form-error" role="alert">{error}</p> : null}<div className="form-actions"><button className="secondary-button" type="button" onClick={()=>navigate(-1)}>Cancel</button><button className="primary-button" type="submit" disabled={busy||!name.trim()||!baseUrl.trim()}>{busy ? <><Spinner /> Saving</> : "Save target"}</button></div></form><aside className="info-card"><span className="info-icon"><Icon name="shield" size={18} /></span><h2>Network policy stays explicit</h2><p>The browser runtime validates the target origin and request destinations. This form never stores target credentials.</p></aside></div></>;
}
