"""complete v1 database schema

Revision ID: 22c2fb02fb02
Revises: a90b3e8daaa1
Create Date: 2026-08-20 00:45:39.399506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22c2fb02fb02'
down_revision: Union[str, Sequence[str], None] = 'a90b3e8daaa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(sa.text("CREATE SCHEMA integration"))
    op.execute(sa.text("CREATE SCHEMA testing"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=150), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('message_key', sa.String(length=200), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events')),
    schema='integration'
    )
    op.create_index(op.f('ix_outbox_events_published_at'), 'outbox_events', ['published_at'], unique=False, schema='integration')
    op.create_table('processed_messages',
    sa.Column('consumer_name', sa.String(length=150), nullable=False),
    sa.Column('message_id', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('partition', sa.Integer(), nullable=True),
    sa.Column('kafka_offset', sa.BigInteger(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('consumer_name', 'message_id', name=op.f('pk_processed_messages')),
    schema='integration'
    )
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'archived')", name='ck_applications_status_allowed'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['core.users.id'], name=op.f('fk_applications_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['core.workspaces.id'], name=op.f('fk_applications_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_applications_workspace_id_id'),
    schema='testing'
    )
    op.create_table('application_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('requires_auth', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'archived')", name='ck_application_targets_status_allowed'),
    sa.ForeignKeyConstraint(['application_id'], ['testing.applications.id'], name=op.f('fk_application_targets_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_targets')),
    sa.UniqueConstraint('application_id', 'id', name='uq_application_targets_application_id_id'),
    schema='testing'
    )
    op.create_table('target_allowed_origins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('scheme', sa.String(length=16), nullable=False),
    sa.Column('hostname', sa.String(length=253), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('include_subdomains', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scheme IN ('http', 'https')", name='ck_target_allowed_origins_scheme_allowed'),
    sa.CheckConstraint('port IS NULL OR (port >= 1 AND port <= 65535)', name='ck_target_allowed_origins_port_range'),
    sa.ForeignKeyConstraint(['target_id'], ['testing.application_targets.id'], name=op.f('fk_target_allowed_origins_target_id_application_targets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_target_allowed_origins')),
    schema='testing'
    )
    op.create_index(op.f('ix_target_allowed_origins_target_id'), 'target_allowed_origins', ['target_id'], unique=False, schema='testing')
    op.create_index('uq_target_allowed_origins_scope', 'target_allowed_origins', ['target_id', 'scheme', 'hostname', 'port', 'include_subdomains'], unique=True, schema='testing', postgresql_nulls_not_distinct=True)
    op.create_table('target_authorizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('authorized_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('authorization_basis', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'authorized', 'revoked', 'expired')", name='ck_target_authorizations_status_allowed'),
    sa.ForeignKeyConstraint(['authorized_by_user_id'], ['core.users.id'], name=op.f('fk_target_authorizations_authorized_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['core.users.id'], name=op.f('fk_target_authorizations_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_id'], ['testing.application_targets.id'], name=op.f('fk_target_authorizations_target_id_application_targets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_target_authorizations')),
    schema='testing'
    )
    op.create_index(op.f('ix_target_authorizations_target_id'), 'target_authorizations', ['target_id'], unique=False, schema='testing')
    op.create_table('test_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('target_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('configuration_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'planning', 'queued', 'running', 'completed', 'failed', 'cancelled')", name='ck_test_runs_status_allowed'),
    sa.ForeignKeyConstraint(['application_id', 'target_id'], ['testing.application_targets.application_id', 'testing.application_targets.id'], name=op.f('fk_test_runs_application_id_application_targets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['core.users.id'], name=op.f('fk_test_runs_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'application_id'], ['testing.applications.workspace_id', 'testing.applications.id'], name=op.f('fk_test_runs_workspace_id_applications'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_runs')),
    schema='testing'
    )
    op.create_index(op.f('ix_test_runs_workspace_id'), 'test_runs', ['workspace_id'], unique=False, schema='testing')
    op.create_table('run_missions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_run_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('success_criteria', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high')", name='ck_run_missions_priority_allowed'),
    sa.CheckConstraint('ordinal >= 1', name='ck_run_missions_ordinal_positive'),
    sa.ForeignKeyConstraint(['test_run_id'], ['testing.test_runs.id'], name=op.f('fk_run_missions_test_run_id_test_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_missions')),
    sa.UniqueConstraint('test_run_id', 'id', name='uq_run_missions_run_id'),
    sa.UniqueConstraint('test_run_id', 'ordinal', name='uq_run_missions_run_ordinal'),
    schema='testing'
    )
    op.create_table('run_personas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_run_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ordinal >= 1', name='ck_run_personas_ordinal_positive'),
    sa.ForeignKeyConstraint(['test_run_id'], ['testing.test_runs.id'], name=op.f('fk_run_personas_test_run_id_test_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_personas')),
    sa.UniqueConstraint('test_run_id', 'id', name='uq_run_personas_run_id'),
    sa.UniqueConstraint('test_run_id', 'ordinal', name='uq_run_personas_run_ordinal'),
    schema='testing'
    )
    op.create_table('persona_journeys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_run_id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ordinal >= 1', name='ck_persona_journeys_ordinal_positive'),
    sa.ForeignKeyConstraint(['test_run_id', 'mission_id'], ['testing.run_missions.test_run_id', 'testing.run_missions.id'], name=op.f('fk_persona_journeys_test_run_id_run_missions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_run_id', 'persona_id'], ['testing.run_personas.test_run_id', 'testing.run_personas.id'], name=op.f('fk_persona_journeys_test_run_id_run_personas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persona_journeys')),
    sa.UniqueConstraint('test_run_id', 'id', name='uq_persona_journeys_run_id'),
    sa.UniqueConstraint('test_run_id', 'ordinal', name='uq_persona_journeys_run_ordinal'),
    sa.UniqueConstraint('test_run_id', 'persona_id', 'mission_id', name='uq_persona_journeys_combination'),
    schema='testing'
    )
    op.create_unique_constraint('uq_user_identities_user_id_id', 'user_identities', ['user_id', 'id'], schema='auth')
    op.drop_constraint(op.f('fk_user_sessions_identity_id_user_identities'), 'user_sessions', schema='auth', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_sessions_user_id_user_identities'), 'user_sessions', 'user_identities', ['user_id', 'identity_id'], ['user_id', 'id'], source_schema='auth', referent_schema='auth', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_sessions_user_id_user_identities'), 'user_sessions', schema='auth', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_sessions_identity_id_user_identities'), 'user_sessions', 'user_identities', ['identity_id'], ['id'], source_schema='auth', referent_schema='auth', ondelete='CASCADE')
    op.drop_constraint('uq_user_identities_user_id_id', 'user_identities', schema='auth', type_='unique')
    op.drop_table('persona_journeys', schema='testing')
    op.drop_table('run_personas', schema='testing')
    op.drop_table('run_missions', schema='testing')
    op.drop_index(op.f('ix_test_runs_workspace_id'), table_name='test_runs', schema='testing')
    op.drop_table('test_runs', schema='testing')
    op.drop_index(op.f('ix_target_authorizations_target_id'), table_name='target_authorizations', schema='testing')
    op.drop_table('target_authorizations', schema='testing')
    op.drop_index('uq_target_allowed_origins_scope', table_name='target_allowed_origins', schema='testing', postgresql_nulls_not_distinct=True)
    op.drop_index(op.f('ix_target_allowed_origins_target_id'), table_name='target_allowed_origins', schema='testing')
    op.drop_table('target_allowed_origins', schema='testing')
    op.drop_table('application_targets', schema='testing')
    op.drop_table('applications', schema='testing')
    op.drop_table('processed_messages', schema='integration')
    op.drop_index(op.f('ix_outbox_events_published_at'), table_name='outbox_events', schema='integration')
    op.drop_table('outbox_events', schema='integration')
    # ### end Alembic commands ###

    op.execute(sa.text("DROP SCHEMA testing"))
    op.execute(sa.text("DROP SCHEMA integration"))
