"""create knowledge and source asset foundation

Revision ID: 417a7f1ee83e
Revises: 8f2e6a1b4c7d
Create Date: 2026-10-01 18:58:27.210894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '417a7f1ee83e'
down_revision: Union[str, Sequence[str], None] = '8f2e6a1b4c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("CREATE SCHEMA knowledge"))
    op.create_table('product_blueprints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived')", name='ck_product_blueprints_status_allowed'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['core.users.id'], name=op.f('fk_product_blueprints_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['core.workspaces.id'], name=op.f('fk_product_blueprints_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_blueprints')),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_product_blueprints_workspace_id_id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_product_blueprints_workspace_name'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_product_blueprints_workspace_id'), 'product_blueprints', ['workspace_id'], unique=False, schema='knowledge')
    op.create_table('blueprint_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('blueprint_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'draft' AND approved_by_user_id IS NULL AND approved_at IS NULL) OR (status = 'approved' AND approved_by_user_id IS NOT NULL AND approved_at IS NOT NULL)", name='ck_blueprint_versions_approval_consistent'),
    sa.CheckConstraint("status IN ('draft', 'approved')", name='ck_blueprint_versions_status_allowed'),
    sa.CheckConstraint('version_number >= 1', name='ck_blueprint_versions_version_positive'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['core.users.id'], name=op.f('fk_blueprint_versions_approved_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['core.users.id'], name=op.f('fk_blueprint_versions_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'blueprint_id'], ['knowledge.product_blueprints.workspace_id', 'knowledge.product_blueprints.id'], name=op.f('fk_blueprint_versions_workspace_id_product_blueprints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blueprint_versions')),
    sa.UniqueConstraint('workspace_id', 'blueprint_id', 'id', name='uq_blueprint_versions_workspace_blueprint_id'),
    sa.UniqueConstraint('workspace_id', 'blueprint_id', 'version_number', name='uq_blueprint_versions_blueprint_version'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_blueprint_versions_workspace_id_id'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_blueprint_versions_blueprint_id'), 'blueprint_versions', ['blueprint_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_blueprint_versions_workspace_id'), 'blueprint_versions', ['workspace_id'], unique=False, schema='knowledge')
    op.create_table('source_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('blueprint_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived')", name='ck_source_assets_status_allowed'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['core.users.id'], name=op.f('fk_source_assets_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'blueprint_id'], ['knowledge.product_blueprints.workspace_id', 'knowledge.product_blueprints.id'], name=op.f('fk_source_assets_workspace_id_product_blueprints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_assets')),
    sa.UniqueConstraint('workspace_id', 'blueprint_id', 'id', name='uq_source_assets_workspace_blueprint_id'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_source_assets_workspace_id_id'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_source_assets_blueprint_id'), 'source_assets', ['blueprint_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_source_assets_workspace_id'), 'source_assets', ['workspace_id'], unique=False, schema='knowledge')
    op.create_table('asset_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('blueprint_id', sa.Uuid(), nullable=False),
    sa.Column('source_asset_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('declared_content_type', sa.String(length=255), nullable=True),
    sa.Column('detected_content_type', sa.String(length=255), nullable=True),
    sa.Column('storage_provider', sa.String(length=16), nullable=False),
    sa.Column('bucket', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=48), server_default=sa.text("'created'"), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('created', 'upload_pending', 'uploaded', 'quarantined', 'validating', 'validated', 'processing', 'extracted', 'normalized', 'included', 'unsupported', 'corrupted', 'infected_or_suspicious', 'password_protected', 'too_large', 'parsing_failed', 'needs_role_confirmation', 'needs_ocr', 'needs_user_review', 'excluded')", name='ck_asset_versions_status_allowed'),
    sa.CheckConstraint("storage_provider IN ('minio', 's3')", name='ck_asset_versions_storage_provider_allowed'),
    sa.CheckConstraint('size_bytes IS NULL OR size_bytes >= 0', name='ck_asset_versions_size_nonnegative'),
    sa.CheckConstraint('version_number >= 1', name='ck_asset_versions_version_positive'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['core.users.id'], name=op.f('fk_asset_versions_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'blueprint_id', 'source_asset_id'], ['knowledge.source_assets.workspace_id', 'knowledge.source_assets.blueprint_id', 'knowledge.source_assets.id'], name=op.f('fk_asset_versions_workspace_id_source_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_versions')),
    sa.UniqueConstraint('storage_provider', 'bucket', 'object_key', name='uq_asset_versions_storage_location'),
    sa.UniqueConstraint('workspace_id', 'blueprint_id', 'id', name='uq_asset_versions_workspace_blueprint_id'),
    sa.UniqueConstraint('workspace_id', 'blueprint_id', 'source_asset_id', 'id', name='uq_asset_versions_source_asset_identity'),
    sa.UniqueConstraint('workspace_id', 'source_asset_id', 'version_number', name='uq_asset_versions_asset_version'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_asset_versions_blueprint_id'), 'asset_versions', ['blueprint_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_asset_versions_source_asset_id'), 'asset_versions', ['source_asset_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_asset_versions_workspace_id'), 'asset_versions', ['workspace_id'], unique=False, schema='knowledge')
    op.create_table('blueprint_version_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('blueprint_id', sa.Uuid(), nullable=False),
    sa.Column('blueprint_version_id', sa.Uuid(), nullable=False),
    sa.Column('source_asset_id', sa.Uuid(), nullable=False),
    sa.Column('asset_version_id', sa.Uuid(), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('roles_confirmed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('roles_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("roles <@ ARRAY['demonstration', 'product_knowledge', 'business_rules', 'safety_policy', 'test_input', 'ground_truth', 'ui_reference', 'persona_evidence', 'environment_configuration']::varchar[]", name='ck_blueprint_version_assets_roles_allowed'),
    sa.CheckConstraint('(roles_confirmed_by_user_id IS NULL AND roles_confirmed_at IS NULL) OR (roles_confirmed_by_user_id IS NOT NULL AND roles_confirmed_at IS NOT NULL)', name='ck_blueprint_version_assets_role_confirmation_consistent'),
    sa.CheckConstraint('cardinality(roles) >= 1', name='ck_blueprint_version_assets_roles_nonempty'),
    sa.ForeignKeyConstraint(['roles_confirmed_by_user_id'], ['core.users.id'], name=op.f('fk_blueprint_version_assets_roles_confirmed_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'blueprint_id', 'blueprint_version_id'], ['knowledge.blueprint_versions.workspace_id', 'knowledge.blueprint_versions.blueprint_id', 'knowledge.blueprint_versions.id'], name=op.f('fk_blueprint_version_assets_workspace_id_blueprint_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'blueprint_id', 'source_asset_id', 'asset_version_id'], ['knowledge.asset_versions.workspace_id', 'knowledge.asset_versions.blueprint_id', 'knowledge.asset_versions.source_asset_id', 'knowledge.asset_versions.id'], name=op.f('fk_blueprint_version_assets_workspace_id_asset_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blueprint_version_assets')),
    sa.UniqueConstraint('workspace_id', 'blueprint_version_id', 'source_asset_id', name='uq_blueprint_version_assets_source'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_blueprint_version_assets_asset_version_id'), 'blueprint_version_assets', ['asset_version_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_blueprint_version_assets_blueprint_id'), 'blueprint_version_assets', ['blueprint_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_blueprint_version_assets_blueprint_version_id'), 'blueprint_version_assets', ['blueprint_version_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_blueprint_version_assets_source_asset_id'), 'blueprint_version_assets', ['source_asset_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_blueprint_version_assets_workspace_id'), 'blueprint_version_assets', ['workspace_id'], unique=False, schema='knowledge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blueprint_version_assets_workspace_id'), table_name='blueprint_version_assets', schema='knowledge')
    op.drop_index(op.f('ix_blueprint_version_assets_source_asset_id'), table_name='blueprint_version_assets', schema='knowledge')
    op.drop_index(op.f('ix_blueprint_version_assets_blueprint_version_id'), table_name='blueprint_version_assets', schema='knowledge')
    op.drop_index(op.f('ix_blueprint_version_assets_blueprint_id'), table_name='blueprint_version_assets', schema='knowledge')
    op.drop_index(op.f('ix_blueprint_version_assets_asset_version_id'), table_name='blueprint_version_assets', schema='knowledge')
    op.drop_table('blueprint_version_assets', schema='knowledge')
    op.drop_index(op.f('ix_asset_versions_workspace_id'), table_name='asset_versions', schema='knowledge')
    op.drop_index(op.f('ix_asset_versions_source_asset_id'), table_name='asset_versions', schema='knowledge')
    op.drop_index(op.f('ix_asset_versions_blueprint_id'), table_name='asset_versions', schema='knowledge')
    op.drop_table('asset_versions', schema='knowledge')
    op.drop_index(op.f('ix_source_assets_workspace_id'), table_name='source_assets', schema='knowledge')
    op.drop_index(op.f('ix_source_assets_blueprint_id'), table_name='source_assets', schema='knowledge')
    op.drop_table('source_assets', schema='knowledge')
    op.drop_index(op.f('ix_blueprint_versions_workspace_id'), table_name='blueprint_versions', schema='knowledge')
    op.drop_index(op.f('ix_blueprint_versions_blueprint_id'), table_name='blueprint_versions', schema='knowledge')
    op.drop_table('blueprint_versions', schema='knowledge')
    op.drop_index(op.f('ix_product_blueprints_workspace_id'), table_name='product_blueprints', schema='knowledge')
    op.drop_table('product_blueprints', schema='knowledge')
    op.execute(sa.text("DROP SCHEMA knowledge"))
    # ### end Alembic commands ###
