"""add evidence and skills foundation

Revision ID: 9edac11ff95c
Revises: ffc4fadf78da
Create Date: 2026-10-01 20:34:49.789089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9edac11ff95c'
down_revision: Union[str, Sequence[str], None] = 'ffc4fadf78da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
