"""create execution evidence and evaluation tables

Revision ID: c3c4b1273287
Revises: 22c2fb02fb02
Create Date: 2026-08-20 00:56:29.524905

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c3c4b1273287"
down_revision: str | Sequence[str] | None = "22c2fb02fb02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(sa.text("CREATE SCHEMA execution"))
    op.execute(sa.text("CREATE SCHEMA evidence"))
    op.execute(sa.text("CREATE SCHEMA evaluation"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("test_run_id", sa.Uuid(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), server_default=sa.text("'open'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('info', 'low', 'medium', 'high', 'critical')",
            name="ck_findings_severity_allowed",
        ),
        sa.CheckConstraint(
            "status IN ('open', 'resolved', 'dismissed')", name="ck_findings_status_allowed"
        ),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["testing.test_runs.id"],
            name=op.f("fk_findings_test_run_id_test_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
        sa.UniqueConstraint("test_run_id", "id", name="uq_findings_test_run_id_id"),
        schema="evaluation",
    )
    op.create_index(
        op.f("ix_findings_test_run_id"),
        "findings",
        ["test_run_id"],
        unique=False,
        schema="evaluation",
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("test_run_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'generating'"), nullable=False
        ),
        sa.Column("executive_summary", sa.Text(), nullable=True),
        sa.Column(
            "report_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('generating', 'completed', 'failed')", name="ck_reports_status_allowed"
        ),
        sa.CheckConstraint("version >= 1", name="ck_reports_version_positive"),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["testing.test_runs.id"],
            name=op.f("fk_reports_test_run_id_test_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint("test_run_id", "version", name="uq_reports_test_run_version"),
        schema="evaluation",
    )
    op.create_index(
        op.f("ix_reports_test_run_id"),
        "reports",
        ["test_run_id"],
        unique=False,
        schema="evaluation",
    )
    op.create_table(
        "finding_journeys",
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("journey_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["evaluation.findings.id"],
            name=op.f("fk_finding_journeys_finding_id_findings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["journey_id"],
            ["testing.persona_journeys.id"],
            name=op.f("fk_finding_journeys_journey_id_persona_journeys"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("finding_id", "journey_id", name=op.f("pk_finding_journeys")),
        schema="evaluation",
    )
    op.create_table(
        "agent_executions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("journey_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.Column(
            "runtime_name",
            sa.String(length=100),
            server_default=sa.text("'google_adk'"),
            nullable=False,
        ),
        sa.Column("model_name", sa.String(length=200), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "outcome IS NULL OR outcome IN ('passed', 'failed', 'partial', 'inconclusive')",
            name="ck_agent_executions_outcome_allowed",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'queued', 'running', 'completed', 'failed', "
            "'timed_out', 'cancelled', 'policy_blocked')",
            name="ck_agent_executions_status_allowed",
        ),
        sa.CheckConstraint("attempt_number >= 1", name="ck_agent_executions_attempt_positive"),
        sa.ForeignKeyConstraint(
            ["journey_id"],
            ["testing.persona_journeys.id"],
            name=op.f("fk_agent_executions_journey_id_persona_journeys"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_executions")),
        sa.UniqueConstraint("id", "journey_id", name="uq_agent_executions_id_journey"),
        sa.UniqueConstraint(
            "journey_id", "attempt_number", name="uq_agent_executions_journey_attempt"
        ),
        schema="execution",
    )
    op.create_index(
        op.f("ix_agent_executions_journey_id"),
        "agent_executions",
        ["journey_id"],
        unique=False,
        schema="execution",
    )
    op.create_table(
        "browser_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("execution_id", sa.Uuid(), nullable=False),
        sa.Column(
            "browser_type",
            sa.String(length=32),
            server_default=sa.text("'chromium'"),
            nullable=False,
        ),
        sa.Column(
            "state", sa.String(length=32), server_default=sa.text("'starting'"), nullable=False
        ),
        sa.Column("context_reference", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('starting', 'open', 'closed', 'failed')",
            name="ck_browser_sessions_state_allowed",
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["execution.agent_executions.id"],
            name=op.f("fk_browser_sessions_execution_id_agent_executions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_browser_sessions")),
        sa.UniqueConstraint("execution_id", "id", name="uq_browser_sessions_execution_id_id"),
        sa.UniqueConstraint("execution_id", name="uq_browser_sessions_execution_id"),
        schema="execution",
    )
    op.create_table(
        "execution_steps",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("execution_id", sa.Uuid(), nullable=False),
        sa.Column("step_number", sa.Integer(), nullable=False),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column("action_summary", sa.Text(), nullable=False),
        sa.Column("observation_summary", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed', 'policy_blocked')",
            name="ck_execution_steps_status_allowed",
        ),
        sa.CheckConstraint("step_number >= 1", name="ck_execution_steps_number_positive"),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["execution.agent_executions.id"],
            name=op.f("fk_execution_steps_execution_id_agent_executions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_steps")),
        sa.UniqueConstraint("execution_id", "id", name="uq_execution_steps_execution_id_id"),
        sa.UniqueConstraint(
            "execution_id", "step_number", name="uq_execution_steps_execution_number"
        ),
        schema="execution",
    )
    op.create_index(
        op.f("ix_execution_steps_execution_id"),
        "execution_steps",
        ["execution_id"],
        unique=False,
        schema="execution",
    )
    op.create_table(
        "run_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("test_run_id", sa.Uuid(), nullable=False),
        sa.Column("journey_id", sa.Uuid(), nullable=True),
        sa.Column("execution_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=150), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["execution.agent_executions.id"],
            name=op.f("fk_run_events_execution_id_agent_executions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["journey_id"],
            ["testing.persona_journeys.id"],
            name=op.f("fk_run_events_journey_id_persona_journeys"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["testing.test_runs.id"],
            name=op.f("fk_run_events_test_run_id_test_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_events")),
        schema="execution",
    )
    op.create_index(
        op.f("ix_run_events_execution_id"),
        "run_events",
        ["execution_id"],
        unique=False,
        schema="execution",
    )
    op.create_index(
        op.f("ix_run_events_journey_id"),
        "run_events",
        ["journey_id"],
        unique=False,
        schema="execution",
    )
    op.create_index(
        op.f("ix_run_events_test_run_id"),
        "run_events",
        ["test_run_id"],
        unique=False,
        schema="execution",
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("execution_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.BigInteger(), nullable=True),
        sa.Column("artifact_type", sa.String(length=32), nullable=False),
        sa.Column("storage_provider", sa.String(length=16), nullable=False),
        sa.Column("bucket", sa.String(length=255), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "artifact_type IN ('screenshot', 'html', 'trace', 'video', "
            "'network_log', 'console_log', 'other')",
            name="ck_artifacts_type_allowed",
        ),
        sa.CheckConstraint(
            "storage_provider IN ('minio', 's3')", name="ck_artifacts_storage_provider_allowed"
        ),
        sa.CheckConstraint(
            "size_bytes IS NULL OR size_bytes >= 0", name="ck_artifacts_size_nonnegative"
        ),
        sa.ForeignKeyConstraint(
            ["execution_id", "step_id"],
            ["execution.execution_steps.execution_id", "execution.execution_steps.id"],
            name=op.f("fk_artifacts_execution_id_execution_steps"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["execution.agent_executions.id"],
            name=op.f("fk_artifacts_execution_id_agent_executions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
        sa.UniqueConstraint(
            "storage_provider", "bucket", "object_key", name="uq_artifacts_storage_location"
        ),
        schema="evidence",
    )
    op.create_index(
        op.f("ix_artifacts_execution_id"),
        "artifacts",
        ["execution_id"],
        unique=False,
        schema="evidence",
    )
    op.create_table(
        "human_action_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("execution_id", sa.Uuid(), nullable=False),
        sa.Column("browser_session_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_step_id", sa.BigInteger(), nullable=True),
        sa.Column("request_type", sa.String(length=32), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "request_type IN ('login', 'password', 'mfa', 'captcha', 'other')",
            name="ck_human_action_requests_type_allowed",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'leased', 'completed', 'cancelled', 'expired')",
            name="ck_human_action_requests_status_allowed",
        ),
        sa.ForeignKeyConstraint(
            ["execution_id", "browser_session_id"],
            ["execution.browser_sessions.execution_id", "execution.browser_sessions.id"],
            name=op.f("fk_human_action_requests_execution_id_browser_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["execution_id", "requested_by_step_id"],
            ["execution.execution_steps.execution_id", "execution.execution_steps.id"],
            name=op.f("fk_human_action_requests_execution_id_execution_steps"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_action_requests")),
        sa.UniqueConstraint("browser_session_id", "id", name="uq_human_action_requests_browser_id"),
        schema="execution",
    )
    op.create_table(
        "policy_decisions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("execution_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.BigInteger(), nullable=True),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("policy_code", sa.String(length=100), nullable=False),
        sa.Column("reason_summary", sa.Text(), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('allowed', 'blocked', 'requires_human')",
            name="ck_policy_decisions_decision_allowed",
        ),
        sa.ForeignKeyConstraint(
            ["execution_id", "step_id"],
            ["execution.execution_steps.execution_id", "execution.execution_steps.id"],
            name=op.f("fk_policy_decisions_execution_id_execution_steps"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["execution.agent_executions.id"],
            name=op.f("fk_policy_decisions_execution_id_agent_executions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_decisions")),
        schema="execution",
    )
    op.create_index(
        op.f("ix_policy_decisions_execution_id"),
        "policy_decisions",
        ["execution_id"],
        unique=False,
        schema="execution",
    )
    op.create_table(
        "finding_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.BigInteger(), nullable=True),
        sa.Column("artifact_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(step_id IS NOT NULL AND artifact_id IS NULL) OR "
            "(step_id IS NULL AND artifact_id IS NOT NULL)",
            name="ck_finding_evidence_exactly_one_reference",
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["evidence.artifacts.id"],
            name=op.f("fk_finding_evidence_artifact_id_artifacts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["evaluation.findings.id"],
            name=op.f("fk_finding_evidence_finding_id_findings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["execution.execution_steps.id"],
            name=op.f("fk_finding_evidence_step_id_execution_steps"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding_evidence")),
        sa.UniqueConstraint(
            "finding_id", "artifact_id", name="uq_finding_evidence_finding_artifact"
        ),
        sa.UniqueConstraint("finding_id", "step_id", name="uq_finding_evidence_finding_step"),
        schema="evaluation",
    )
    op.create_index(
        op.f("ix_finding_evidence_finding_id"),
        "finding_evidence",
        ["finding_id"],
        unique=False,
        schema="evaluation",
    )
    op.create_table(
        "human_control_leases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("browser_session_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("lease_token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "acquired_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["browser_session_id", "request_id"],
            [
                "execution.human_action_requests.browser_session_id",
                "execution.human_action_requests.id",
            ],
            name=op.f("fk_human_control_leases_browser_session_id_human_action_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["browser_session_id"],
            ["execution.browser_sessions.id"],
            name=op.f("fk_human_control_leases_browser_session_id_browser_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["core.users.id"],
            name=op.f("fk_human_control_leases_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_control_leases")),
        sa.UniqueConstraint("lease_token_hash", name="uq_human_control_leases_token_hash"),
        schema="execution",
    )
    op.create_index(
        op.f("ix_human_control_leases_user_id"),
        "human_control_leases",
        ["user_id"],
        unique=False,
        schema="execution",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_human_control_leases_user_id"),
        table_name="human_control_leases",
        schema="execution",
    )
    op.drop_table("human_control_leases", schema="execution")
    op.drop_index(
        op.f("ix_finding_evidence_finding_id"), table_name="finding_evidence", schema="evaluation"
    )
    op.drop_table("finding_evidence", schema="evaluation")
    op.drop_index(
        op.f("ix_policy_decisions_execution_id"), table_name="policy_decisions", schema="execution"
    )
    op.drop_table("policy_decisions", schema="execution")
    op.drop_table("human_action_requests", schema="execution")
    op.drop_index(op.f("ix_artifacts_execution_id"), table_name="artifacts", schema="evidence")
    op.drop_table("artifacts", schema="evidence")
    op.drop_index(op.f("ix_run_events_test_run_id"), table_name="run_events", schema="execution")
    op.drop_index(op.f("ix_run_events_journey_id"), table_name="run_events", schema="execution")
    op.drop_index(op.f("ix_run_events_execution_id"), table_name="run_events", schema="execution")
    op.drop_table("run_events", schema="execution")
    op.drop_index(
        op.f("ix_execution_steps_execution_id"), table_name="execution_steps", schema="execution"
    )
    op.drop_table("execution_steps", schema="execution")
    op.drop_table("browser_sessions", schema="execution")
    op.drop_index(
        op.f("ix_agent_executions_journey_id"), table_name="agent_executions", schema="execution"
    )
    op.drop_table("agent_executions", schema="execution")
    op.drop_table("finding_journeys", schema="evaluation")
    op.drop_index(op.f("ix_reports_test_run_id"), table_name="reports", schema="evaluation")
    op.drop_table("reports", schema="evaluation")
    op.drop_index(op.f("ix_findings_test_run_id"), table_name="findings", schema="evaluation")
    op.drop_table("findings", schema="evaluation")
    # ### end Alembic commands ###

    op.execute(sa.text("DROP SCHEMA evaluation"))
    op.execute(sa.text("DROP SCHEMA evidence"))
    op.execute(sa.text("DROP SCHEMA execution"))
