"""add evidence and skills foundation

Revision ID: ffc4fadf78da
Revises: 417a7f1ee83e
Create Date: 2026-10-01 19:51:17.829468

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffc4fadf78da'
down_revision: str | Sequence[str] | None = '417a7f1ee83e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('blueprint_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived')", name='ck_skills_status_allowed'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['core.users.id'], name=op.f('fk_skills_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'blueprint_id'], ['knowledge.product_blueprints.workspace_id', 'knowledge.product_blueprints.id'], name=op.f('fk_skills_workspace_id_product_blueprints'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('workspace_id', 'blueprint_id', 'id', name='uq_skills_workspace_blueprint_id'),
    sa.UniqueConstraint('workspace_id', 'blueprint_id', 'name', name='uq_skills_blueprint_name'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_skills_blueprint_id'), 'skills', ['blueprint_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_skills_workspace_id'), 'skills', ['workspace_id'], unique=False, schema='knowledge')
    op.create_table('skill_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('blueprint_id', sa.Uuid(), nullable=False),
    sa.Column('blueprint_version_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('grounding_confidence', sa.String(length=16), nullable=True),
    sa.Column('definition_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'draft' AND approved_by_user_id IS NULL AND approved_at IS NULL) OR (status = 'approved' AND approved_by_user_id IS NOT NULL AND approved_at IS NOT NULL)", name='ck_skill_versions_approval_consistent'),
    sa.CheckConstraint("grounding_confidence IS NULL OR grounding_confidence IN ('low', 'medium', 'high')", name='ck_skill_versions_grounding_confidence_allowed'),
    sa.CheckConstraint("status IN ('draft', 'approved')", name='ck_skill_versions_status_allowed'),
    sa.CheckConstraint('version_number >= 1', name='ck_skill_versions_version_positive'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['core.users.id'], name=op.f('fk_skill_versions_approved_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['core.users.id'], name=op.f('fk_skill_versions_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'blueprint_id', 'blueprint_version_id'], ['knowledge.blueprint_versions.workspace_id', 'knowledge.blueprint_versions.blueprint_id', 'knowledge.blueprint_versions.id'], name=op.f('fk_skill_versions_workspace_id_blueprint_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'blueprint_id', 'skill_id'], ['knowledge.skills.workspace_id', 'knowledge.skills.blueprint_id', 'knowledge.skills.id'], name=op.f('fk_skill_versions_workspace_id_skills'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_versions')),
    sa.UniqueConstraint('workspace_id', 'blueprint_id', 'id', name='uq_skill_versions_workspace_blueprint_id'),
    sa.UniqueConstraint('workspace_id', 'blueprint_version_id', 'skill_id', name='uq_skill_versions_blueprint_version_skill'),
    sa.UniqueConstraint('workspace_id', 'skill_id', 'version_number', name='uq_skill_versions_skill_version'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_skill_versions_blueprint_id'), 'skill_versions', ['blueprint_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_skill_versions_blueprint_version_id'), 'skill_versions', ['blueprint_version_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_skill_versions_skill_id'), 'skill_versions', ['skill_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_skill_versions_workspace_id'), 'skill_versions', ['workspace_id'], unique=False, schema='knowledge')
    op.create_table('evidence_units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('blueprint_id', sa.Uuid(), nullable=False),
    sa.Column('asset_version_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_locator', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('extractor_name', sa.String(length=128), nullable=False),
    sa.Column('extractor_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("evidence_type IN ('text', 'table', 'image', 'video_segment', 'structured_data')", name='ck_evidence_units_type_allowed'),
    sa.CheckConstraint('content_text IS NOT NULL OR content_json IS NOT NULL', name='ck_evidence_units_content_present'),
    sa.ForeignKeyConstraint(['workspace_id', 'blueprint_id', 'asset_version_id'], ['knowledge.asset_versions.workspace_id', 'knowledge.asset_versions.blueprint_id', 'knowledge.asset_versions.id'], name=op.f('fk_evidence_units_workspace_id_asset_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_units')),
    sa.UniqueConstraint('workspace_id', 'asset_version_id', 'extractor_name', 'extractor_version', 'ordinal', name='uq_evidence_units_extraction_position'),
    sa.UniqueConstraint('workspace_id', 'blueprint_id', 'id', name='uq_evidence_units_workspace_blueprint_id'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_evidence_units_asset_version_id'), 'evidence_units', ['asset_version_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_evidence_units_blueprint_id'), 'evidence_units', ['blueprint_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_evidence_units_workspace_id'), 'evidence_units', ['workspace_id'], unique=False, schema='knowledge')
    op.create_table('skill_evidence_references',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('blueprint_id', sa.Uuid(), nullable=False),
    sa.Column('skill_version_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_unit_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'blueprint_id', 'evidence_unit_id'], ['knowledge.evidence_units.workspace_id', 'knowledge.evidence_units.blueprint_id', 'knowledge.evidence_units.id'], name=op.f('fk_skill_evidence_references_workspace_id_evidence_units'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'blueprint_id', 'skill_version_id'], ['knowledge.skill_versions.workspace_id', 'knowledge.skill_versions.blueprint_id', 'knowledge.skill_versions.id'], name=op.f('fk_skill_evidence_references_workspace_id_skill_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_evidence_references')),
    sa.UniqueConstraint('workspace_id', 'skill_version_id', 'evidence_unit_id', name='uq_skill_evidence_reference'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_skill_evidence_references_blueprint_id'), 'skill_evidence_references', ['blueprint_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_skill_evidence_references_evidence_unit_id'), 'skill_evidence_references', ['evidence_unit_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_skill_evidence_references_skill_version_id'), 'skill_evidence_references', ['skill_version_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_skill_evidence_references_workspace_id'), 'skill_evidence_references', ['workspace_id'], unique=False, schema='knowledge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_evidence_references_workspace_id'), table_name='skill_evidence_references', schema='knowledge')
    op.drop_index(op.f('ix_skill_evidence_references_skill_version_id'), table_name='skill_evidence_references', schema='knowledge')
    op.drop_index(op.f('ix_skill_evidence_references_evidence_unit_id'), table_name='skill_evidence_references', schema='knowledge')
    op.drop_index(op.f('ix_skill_evidence_references_blueprint_id'), table_name='skill_evidence_references', schema='knowledge')
    op.drop_table('skill_evidence_references', schema='knowledge')
    op.drop_index(op.f('ix_evidence_units_workspace_id'), table_name='evidence_units', schema='knowledge')
    op.drop_index(op.f('ix_evidence_units_blueprint_id'), table_name='evidence_units', schema='knowledge')
    op.drop_index(op.f('ix_evidence_units_asset_version_id'), table_name='evidence_units', schema='knowledge')
    op.drop_table('evidence_units', schema='knowledge')
    op.drop_index(op.f('ix_skill_versions_workspace_id'), table_name='skill_versions', schema='knowledge')
    op.drop_index(op.f('ix_skill_versions_skill_id'), table_name='skill_versions', schema='knowledge')
    op.drop_index(op.f('ix_skill_versions_blueprint_version_id'), table_name='skill_versions', schema='knowledge')
    op.drop_index(op.f('ix_skill_versions_blueprint_id'), table_name='skill_versions', schema='knowledge')
    op.drop_table('skill_versions', schema='knowledge')
    op.drop_index(op.f('ix_skills_workspace_id'), table_name='skills', schema='knowledge')
    op.drop_index(op.f('ix_skills_blueprint_id'), table_name='skills', schema='knowledge')
    op.drop_table('skills', schema='knowledge')
    # ### end Alembic commands ###
